# -*- coding: utf-8 -*-
"""Exp2a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18B9-D0nmF3jP2F8bb5qv9a56a9srUOPM
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load an image
image = cv2.imread('/content/61H6elOlc+L._SL1280_.jpg')  # Replace with your image path
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # Convert from BGR to RGB for displaying

# 1. Smoothing (Blurring) using Gaussian Blur
smooth_image = cv2.GaussianBlur(image, (5, 5), 0)

# 2. Sharpening using a kernel
# A kernel for sharpening is usually something like this:
kernel_sharpen = np.array([[0, -1, 0],
                           [-1, 5,-1],
                           [0, -1, 0]])

sharpened_image = cv2.filter2D(image, -1, kernel_sharpen)

# Displaying the images
plt.figure(figsize=(10, 10))

# Original Image
plt.subplot(1, 3, 1)
plt.imshow(image)
plt.title('Original Image')
plt.axis('off')
plt.subplot(1, 3, 2)
plt.imshow(sharpened_image)
plt.title('sharpened Image')
plt.axis('off')