# -*- coding: utf-8 -*-
"""Exp2b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6PscqidAhuyfewe41K3_nh4WQmJLA1W
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load an image
image = cv2.imread('/content/61H6elOlc+L._SL1280_.jpg')

# Convert the image to RGB (OpenCV loads images in BGR format)
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Apply Mean (Average) Blur
mean_blurred = cv2.blur(image, (5, 5))

# Apply Gaussian Blur
gaussian_blurred = cv2.GaussianBlur(image, (5, 5), 0)

# Apply Median Blur
median_blurred = cv2.medianBlur(image, 5)

# Display the images
plt.figure(figsize=(10, 10))

# Original Image
plt.subplot(2, 2, 1)
plt.imshow(image_rgb)
plt.title('Original Image')
plt.axis('off')

# Mean Blur
plt.subplot(2, 2, 2)
plt.imshow(cv2.cvtColor(mean_blurred, cv2.COLOR_BGR2RGB))
plt.title('Mean Blur')
plt.axis('off')

# Gaussian Blur
plt.subplot(2, 2, 3)
plt.imshow(cv2.cvtColor(gaussian_blurred, cv2.COLOR_BGR2RGB))
plt.title('Gaussian Blur')
plt.axis('off')

# Median Blur
plt.subplot(2, 2, 4)
plt.imshow(cv2.cvtColor(median_blurred, cv2.COLOR_BGR2RGB))
plt.title('Median Blur')
plt.axis('off')